### ISSUE TITLE
Registered attendees not visible to organizers

### ISSUE THREAD

**Issue by micheleleah** [dancerfly/django-brambling#825] opened 2016-10-27 20:46 UTC
Just got a request from a user:

> We've had reports that people have registered on line for our event, but we don't get the Dancerfly emails, and they don't appear in the list of attendees visible to the event organizers.

**Comment by harrislapiroff** [comment] 2016-10-27 20:49
I suspect this is a case in which the attendees have not actually successfully completed registration (which may well be a UI problem if people think they're registering but aren't). It's possible that there's a bug in our system preventing completed registrations from showing up, but, based on the fact that there is no record of these registrants anywhere and we haven't heard of this bug before, I think the first explanation is more likely. I am responding to the user with a request for more information.

**Comment by raq929** [comment] 2017-05-16 14:49
@harrislapiroff did the user give you more info?

**Comment by harrislapiroff** [comment] 2017-05-16 15:13
Nope!

**Comment by harrislapiroff** [comment] 2017-05-16 15:13
I am inclined to call this user error (or at most a UI problem that we have no information for) and not a bug.

**Comment by melinath** [comment] 2020-04-13 19:50
Closing due to lack of information.

**Closed by melinath** 2020-04-13 19:50 UTC
Labels: bug, high priority
